info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"

server:
  port: 9029

spring:
  datasource:
    url: jdbc:mysql://172.26.130.75:4000/pigeon-test?useSSL=false&serverTimezone=Asia/Shanghai
    username: yn_usr
    password: seal_admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: true
      pool-name: HikaraiCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: 172.26.130.28
    port: 8001
    password: Seal@Ucan
    timeout: 2000ms
    database: 3


mybatis:
  mapper-locations: classpath*:/mybatis/mapper/**/*.xml
  config-location: classpath:/mybatis/mybatis-config.xml

pigeon:
  sign-switch: false
