info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"

server:
  port: 8989

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pigeon?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: true
      pool-name: HikaraiCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: localhost
    port: 6379
#    password:
    database: 0
#    redisson: redisson-single.yml

mybatis:
  mapper-locations: classpath*:/mybatis/mapper/**/*.xml
  config-location: classpath:/mybatis/mybatis-config.xml

pigeon:
  sign-switch: false